
CREATE DATABASE [{Database}] ON  PRIMARY 
( NAME = N'{Database}', FILENAME = N'C:\Database\{Database}\{Database}.mdf' , SIZE = 151296KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB ), 
 FILEGROUP [{Database}Dat] 
( NAME = N'{Database}Dat', FILENAME = N'C:\Database\{Database}\{Database}.ndf' , SIZE = 592896KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'{Database}Log', FILENAME = N'C:\Database\{Database}\{Database}.ldf' , SIZE = 84032KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)

EXEC dbo.sp_dbcmptlevel @dbname=N'{Database}', @new_cmptlevel=80

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [{Database}].[dbo].[sp_fulltext_database] @action = 'disable'
end

ALTER DATABASE [{Database}] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [{Database}] SET ANSI_NULLS OFF 
ALTER DATABASE [{Database}] SET ANSI_PADDING OFF 
ALTER DATABASE [{Database}] SET ANSI_WARNINGS OFF 
ALTER DATABASE [{Database}] SET ARITHABORT OFF 
ALTER DATABASE [{Database}] SET AUTO_CLOSE OFF 
ALTER DATABASE [{Database}] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [{Database}] SET AUTO_SHRINK OFF 
ALTER DATABASE [{Database}] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [{Database}] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [{Database}] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [{Database}] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [{Database}] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [{Database}] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [{Database}] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [{Database}] SET  DISABLE_BROKER 
ALTER DATABASE [{Database}] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [{Database}] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [{Database}] SET TRUSTWORTHY OFF 
ALTER DATABASE [{Database}] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [{Database}] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [{Database}] SET  READ_WRITE 
ALTER DATABASE [{Database}] SET RECOVERY SIMPLE 
ALTER DATABASE [{Database}] SET  MULTI_USER 
ALTER DATABASE [{Database}] SET PAGE_VERIFY TORN_PAGE_DETECTION  
ALTER DATABASE [{Database}] SET DB_CHAINING OFF 